### ISSUE TITLE
Prototype 0.1.1 Roadmap

### ISSUE THREAD

**Issue by Sckiii** [Sckiii/Fish-Game-2-Attack-of-the-Shrimps#10]
- [x] Have a working screen with dialogue (and maybe characters)

**Comment by Sckiii** [comment]
- [ ] Main box
- [ ] Text box
- [ ] Characters on either side of the screen
- [ ] Reusable format
- [ ] (Preferably only on one html file)

**Comment by Sckiii** [comment]
Just need characters now

**Comment by Sckiii** [comment]
I'll just add characters to Prototype 0.1.2
