### ISSUE TITLE
Prototype 0.1.2 Roadmap

### ISSUE THREAD

**Issue by Sckiii** [Sckiii/Fish-Game-2-Attack-of-the-Shrimps#17]
- [ ] Characters overlayed on the screen
- [ ] Story of Chapter 1
- [ ] Finish Chapter 1 html

**Comment by Sckiii** [comment]
This is less technical heavy, but yeah
